# Generated by Django 5.0.1 on 2025-12-21 06:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0003_chatconversation_chatroommessage_conversationmessage_and_more'),
        ('monitoring', '0003_alter_classsession_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='announcement',
            old_name='is_published',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='announcement',
            old_name='posted_by',
            new_name='teacher',
        ),
        migrations.RemoveField(
            model_name='announcement',
            name='image',
        ),
        migrations.AddField(
            model_name='announcement',
            name='class_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='monitoring.class'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='is_pinned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='announcement',
            name='is_school_wide',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='announcement',
            name='scheduled_publish',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='announcement',
            name='target_levels',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='target_audience',
            field=models.CharField(default='all', max_length=200),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
