# Generated by Django 5.0.1 on 2025-12-21 07:14

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0004_rename_is_published_announcement_is_active_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('grade', 'Grade Entry'), ('attendance', 'Attendance Record'), ('announcement', 'Announcement'), ('message', 'Message Sent'), ('event', 'Event')], max_length=20)),
                ('description', models.TextField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('related_object_id', models.IntegerField(blank=True, null=True)),
                ('related_object_type', models.CharField(blank=True, max_length=50, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Activities',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='information_timesta_c4f090_idx'), models.Index(fields=['user', '-timestamp'], name='information_user_id_5a836e_idx')],
            },
        ),
    ]
