# Generated by Django 5.0.1 on 2025-12-21 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0005_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='image',
            field=models.ImageField(blank=True, help_text='Banner image for announcement', null=True, upload_to='announcements/images/'),
        ),
    ]
