# Generated by Django 5.0.1 on 2025-12-25 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('monitoring', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='child',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='users.child'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='recorded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.teacher'),
        ),
        migrations.AddField(
            model_name='attendancesummary',
            name='child',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_summaries', to='users.child'),
        ),
        migrations.AddField(
            model_name='class',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='users.teacher'),
        ),
        migrations.AddField(
            model_name='attendancesummary',
            name='class_obj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_summaries', to='monitoring.class'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='class_obj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='monitoring.class'),
        ),
        migrations.AddField(
            model_name='competency',
            name='domain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competencies', to='monitoring.domain'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='class_obj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='monitoring.class'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='users.child'),
        ),
        migrations.AddField(
            model_name='quarterlycompetencyrecord',
            name='child',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competency_records', to='users.child'),
        ),
        migrations.AddField(
            model_name='quarterlycompetencyrecord',
            name='competency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='monitoring.competency'),
        ),
        migrations.AddField(
            model_name='quarterlycompetencyrecord',
            name='recorded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.teacher'),
        ),
        migrations.AddField(
            model_name='quarterlysummary',
            name='child',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quarterly_summaries', to='users.child'),
        ),
        migrations.AddField(
            model_name='quarterlysummary',
            name='class_obj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quarterly_summaries', to='monitoring.class'),
        ),
        migrations.AddField(
            model_name='quarterlysummary',
            name='recorded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.teacher'),
        ),
        migrations.AlterUniqueTogether(
            name='attendancesummary',
            unique_together={('child', 'month', 'class_obj')},
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['child', '-date'], name='monitoring__child_i_070c00_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['date', 'class_obj'], name='monitoring__date_c5fdb8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('child', 'date', 'class_obj')},
        ),
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together={('student', 'class_obj')},
        ),
        migrations.AddIndex(
            model_name='quarterlycompetencyrecord',
            index=models.Index(fields=['child', 'quarter'], name='monitoring__child_i_02a334_idx'),
        ),
        migrations.AddIndex(
            model_name='quarterlycompetencyrecord',
            index=models.Index(fields=['competency', 'quarter'], name='monitoring__compete_27cf0b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='quarterlycompetencyrecord',
            unique_together={('child', 'competency', 'quarter')},
        ),
        migrations.AlterUniqueTogether(
            name='quarterlysummary',
            unique_together={('child', 'quarter', 'class_obj')},
        ),
    ]
