# Generated by Django 5.0.1 on 2025-12-21 20:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('monitoring', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='child',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='users.child'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='recorded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.teacher'),
        ),
        migrations.AddField(
            model_name='attendancesummary',
            name='child',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_summaries', to='users.child'),
        ),
        migrations.AddField(
            model_name='class',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='users.teacher'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='class_obj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='monitoring.class'),
        ),
        migrations.AddField(
            model_name='classsession',
            name='class_obj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='monitoring.class'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='class_obj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='monitoring.class'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='users.child'),
        ),
        migrations.AddField(
            model_name='finalgrade',
            name='class_obj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='final_grades', to='monitoring.class'),
        ),
        migrations.AddField(
            model_name='finalgrade',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='final_grades', to='users.child'),
        ),
        migrations.AddField(
            model_name='gradeitem',
            name='class_obj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_items', to='monitoring.class'),
        ),
        migrations.AddField(
            model_name='gradeitem',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_items', to='users.child'),
        ),
        migrations.AddField(
            model_name='gradingscheme',
            name='class_obj',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='grading_scheme', to='monitoring.class'),
        ),
        migrations.AlterUniqueTogether(
            name='attendancesummary',
            unique_together={('child', 'month')},
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('child', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='classsession',
            unique_together={('class_obj', 'date', 'class_obj')},
        ),
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together={('student', 'class_obj')},
        ),
        migrations.AlterUniqueTogether(
            name='finalgrade',
            unique_together={('student', 'class_obj', 'quarter')},
        ),
    ]
