# Generated by Django 5.0.1 on 2025-12-21 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0002_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='classsession',
            unique_together={('class_obj', 'date', 'class_obj')},
        ),
    ]
