# Generated by Django 5.0.1 on 2025-12-21 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0003_alter_classsession_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='class_obj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='monitoring.class'),
        ),
    ]
